language: node_js
node_js:
- stable
deploy:
  provider: heroku
  api_key:
    secure: ctSity64+PnjU8W1TVq2SjiBOP0hHsUoTmMqXewDwk6Ew7Q4Z1ukgU5AOtYtFJsOQikC7vkMfm5Vhxh3VsSGnU83Er5EfplXgc5OKTbdFXmv43oa9TCbtnfne33mbGaStqkCdhuLrHOx2O80ql34Z7N87YH2JZLHBzmHtLo/ASVSoGmnjgbWm9Qfh07xqZEWuL74vFggHGQzn2qNCBrLqUO9T2x6fROsFEtuEe8mSSjse/W+UhjB/civ3urn6Eez1RPrbrsNKPdHpISAHvAxY5G6ytI2XXxgf9s3QsxGi4Aj9HGwreQqJMbIA1QDh9euXNZHJCLiDWX+FW3goLM2xYpEX+XmeSxIYNkqTGvnzQEf8lEUWZFs2HxIHoNjFMSlqd521wrg64q+IXBFrkZgNOe+8Lx4VkCYRb22lRptnYYD5Dj3WBEQpVsKv1R1Mdwu5uZ81PjsFV0xpe92p0wz28NA191i+Ird0SIKWXgd1OzD2ey6UKQFx3gJOPTxBk15aS2+DjcTPXbe/GT3ZM/rUiQK710q/6VyF2USJdRIv59eK0LIdt/k78I8WB0G5Lqeqx5Y+C8fPlwLqexKIui/GH+KkcFP/0qT/omehe3l0I43wnwLlRbYlfv+U0cKWI+zTOLVCE5rkayEkS0qTKXS+ev4NZHmEVX3sZ5xvAhJEuw=
  on:
    all_branches: true
